import os
from dotenv import load_dotenv
import psycopg2

load_dotenv()

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)

if not DATABASE_URL:
    raise RuntimeError("Missing DATABASE_URL in .env")

SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  profile_completed BOOLEAN DEFAULT FALSE,
  age INTEGER,
  goal VARCHAR(255),
  exercise_time TIME,
  notifications_per_week INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  stage VARCHAR(100),
  type VARCHAR(100),
  frequency VARCHAR(100),
  duration VARCHAR(100),
  next_exercise VARCHAR(100),
  injury_area VARCHAR(100),
  injury_type VARCHAR(100),
  reminder VARCHAR(10),
  avatar VARCHAR(255) DEFAULT 'default.png',
  theme VARCHAR(10) DEFAULT 'Light',
  language VARCHAR(5) DEFAULT 'el'
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_email_unique') THEN
    ALTER TABLE users ADD CONSTRAINT users_email_unique UNIQUE (email);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS game_statistics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100),
  age INTEGER,
  game_name VARCHAR(100),
  score DOUBLE PRECISION,
  time_seconds DOUBLE PRECISION,
  result VARCHAR(50),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


"""

print("Connecting to Postgres...")
conn = psycopg2.connect(DATABASE_URL)
conn.autocommit = True
cur = conn.cursor()

print("Creating tables...")
cur.execute(SCHEMA_SQL)

cur.close()
conn.close()
print("Done ✅ Tables created.")
